# Generated by Django 6.0.2 on 2026-02-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/149/149071.png', upload_to='profile_pics/'),
        ),
    ]
