# Generated by Django 6.0.2 on 2026-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
