# Generated by Django 6.0.2 on 2026-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/def.png', null=True, upload_to='profile_pics/'),
        ),
    ]
