# Generated by Django 6.0.2 on 2026-02-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_course_description_course_price_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
